import { Campaign, NewCampaign } from '../../types/campaign';

export const campaignTemplate: NewCampaign = {
  name: '',
  description: '',
  acl: {},
  skills: [],
  characters: [],
};

export const campaign: Campaign = {
  id: 'c1',
  name: 'Tales of Dinosaurs and Stuff',
  description: 'also Time Travel and Alien Spaceships',
  characters: [
    'ry',
    'connie',
    'momentusUndergrave',
    'chad',
    'thomson',
    'sparks',
    'biscuit',
    'drFanta',
    'smammal',
    'nugget',
  ],
  acl: {
    'eric.eslinger@gmail.com': 'admin',
    'eric.eslinger+tales@gmail.com': 'read',
    'llahwehttam@gmail.com': 'read',
    'guy@albertelli.com': 'read',
    'megan@albertelli.com': 'read',
    'cljacobs1975@gmail.com': 'read',
    'phil.bowen@gmail.com': 'read',
  },
  skills: [
    'advancedsecurity',
    'commandanimal',
    'convictiondefense',
    'convictionmeleeattack',
    'convictionrangedattack',
    'dryscienceknowledge',
    'drysciencetinker',
    'focusdefense',
    'focusmeleeattack',
    'focusrangedattack',
    'hacking',
    'healthdefense',
    'initiative',
    'intimidate',
    'legerdemain',
    'lie',
    'medicine',
    'mightdefense',
    'mightmeleeattack',
    'mightrangedattack',
    'movement',
    'otherknowledge',
    'perception',
    'persuade',
    'picklocks',
    'piloting',
    'riding',
    'sensemotive',
    'sneaking',
    'speeddefense',
    'speedmeleeattack',
    'speedrangedattack',
    'swimming',
    'wetscienceknowledge',
    'wetsciencetinker',
    'wildernesslore',
  ],
};
