import { CharacterSkill, LevelNames } from '../../types/skill';
import { Companion, PlayerCharacter } from '../../types/character';

import { AttributeNames } from '../../types/attribute';
import { campaign } from './campaign.js';
import { playerTemplate } from './characterTemplates.js';
import { skillSeed } from './skills.js';

function skill(s: string, l: LevelNames): CharacterSkill {
  return { ...skillSeed[s], level: l };
}

const baseSkills: Record<string, CharacterSkill> = campaign.skills.reduce(
  (acc, curr) => ({ ...acc, [curr]: skill(curr, 'unskilled') }),
  {}
);

function attr<T extends AttributeNames>(v: number, e: number, n: T) {
  return {
    name: n,
    edge: e,
    current: v,
    pool: v,
    wound: false,
  };
}

export const players: PlayerCharacter[] = [
  {
    id: 'ry',
    campaign: 'c1',
    name: 'Ry McGinnis',
    acl: {
      'cljacobs1975@gmail.com': 'admin',
      'eric.eslinger+tales@gmail.com': 'admin',
    },
    description: '',
    type: 'player',
    attributes: {
      health: attr(10, 0, 'health'),
      might: attr(5, 0, 'might'),
      speed: attr(5, 0, 'speed'),
      focus: attr(10, 1, 'focus'),
      conviction: attr(7, 0, 'conviction'),
    },
    skills: {
      ...baseSkills,
      advancedsecurity: skill('advancedsecurity', 'trained'),
      commandanimal: skill('commandanimal', 'proficient'),
      convictiondefense: skill('convictiondefense', 'proficient'),
      dryscienceknowledge: skill('dryscienceknowledge', 'proficient'),
      drysciencetinker: skill('drysciencetinker', 'proficient'),
      focusdefense: skill('focusdefense', 'proficient'),
      hacking: skill('hacking', 'proficient'),
      healthdefense: skill('healthdefense', 'proficient'),
      initiative: skill('initiative', 'proficient'),
      legerdemain: skill('legerdemain', 'proficient'),
      mightdefense: skill('mightdefense', 'proficient'),
      movement: skill('movement', 'proficient'),
      perception: skill('perception', 'proficient'),
      persuade: skill('persuade', 'proficient'),
      picklocks: skill('picklocks', 'proficient'),
      piloting: skill('piloting', 'proficient'),
      sensemotive: skill('sensemotive', 'proficient'),
      sneaking: skill('sneaking', 'proficient'),
      speeddefense: skill('speeddefense', 'proficient'),
    },
    experience: 27,
    initiative: 0,
  },
  {
    id: 'connie',
    campaign: 'c1',
    name: 'Connecticut (Connie) Butler',
    acl: {
      'megan@albertelli.com': 'admin',
    },
    description: '',
    type: 'player',
    attributes: {
      health: attr(10, 0, 'health'),
      might: attr(5, 0, 'might'),
      speed: attr(5, 0, 'speed'),
      focus: attr(7, 0, 'focus'),
      conviction: attr(10, 2, 'conviction'),
    },
    skills: {
      ...playerTemplate.skills,
      dryscienceknowledge: skill('dryscienceknowledge', 'inept'),
      drysciencetinker: skill('drysciencetinker', 'inept'),
      healthdefense: skill('healthdefense', 'proficient'),
      legerdemain: skill('legerdemain', 'proficient'),
      lie: skill('lie', 'proficient'),
      medicine: skill('medicine', 'proficient'),
      mightdefense: skill('mightdefense', 'proficient'),
      otherknowledge: skill('otherknowledge', 'inept'),
      perception: skill('perception', 'proficient'),
      persuade: skill('persuade', 'proficient'),
      sneaking: skill('sneaking', 'proficient'),
      wetscienceknowledge: skill('wetscienceknowledge', 'inept'),
      wetsciencetinker: skill('wetsciencetinker', 'inept'),
      wildernesslore: skill('wildernesslore', 'proficient'),
    },
    experience: 34,
    initiative: 0,
  },
  {
    id: 'momentusUndergrave',
    campaign: 'c1',
    name: 'Momentus Undergrave',
    acl: {
      'llahwehttam@gmail.com': 'admin',
    },
    description: '',
    type: 'player',
    attributes: {
      health: attr(10, 0, 'health'),
      might: attr(5, 0, 'might'),
      speed: attr(7, 0, 'speed'),
      focus: attr(10, 1, 'focus'),
      conviction: attr(5, 0, 'conviction'),
    },
    skills: {
      ...playerTemplate.skills,
      commandanimal: skill('commandanimal', 'trained'),
      healthdefense: skill('healthdefense', 'proficient'),
      initiative: skill('initiative', 'proficient'),
      intimidate: skill('intimidate', 'inept'),
      lie: skill('lie', 'inept'),
      medicine: skill('medicine', 'proficient'),
      mightdefense: skill('mightdefense', 'proficient'),
      perception: skill('perception', 'proficient'),
      persuade: skill('persuade', 'inept'),
      sensemotive: skill('sensemotive', 'inept'),
      wetscienceknowledge: skill('wetscienceknowledge', 'proficient'),
      wetsciencetinker: skill('wetsciencetinker', 'proficient'),
      wildernesslore: skill('wildernesslore', 'proficient'),
    },
    experience: 22,
    initiative: 0,
  },
  {
    id: 'chad',
    campaign: 'c1',
    name: 'Chad',
    acl: {
      'guy@albertelli.com': 'admin',
    },
    description: '',
    type: 'player',
    attributes: {
      health: attr(10, 0, 'health'),
      might: attr(10, 2, 'might'),
      speed: attr(6, 1, 'speed'),
      focus: attr(5, 0, 'focus'),
      conviction: attr(7, 0, 'conviction'),
    },
    skills: {
      ...playerTemplate.skills,
      convictiondefense: skill('convictiondefense', 'proficient'),
      dryscienceknowledge: skill('dryscienceknowledge', 'inept'),
      drysciencetinker: skill('drysciencetinker', 'inept'),
      focusdefense: skill('focusdefense', 'proficient'),
      healthdefense: skill('healthdefense', 'proficient'),
      initiative: skill('initiative', 'proficient'),
      medicine: skill('medicine', 'proficient'),
      mightdefense: skill('mightdefense', 'proficient'),
      otherknowledge: skill('otherknowledge', 'inept'),
      wetscienceknowledge: skill('wetscienceknowledge', 'inept'),
      wetsciencetinker: skill('wetsciencetinker', 'inept'),
    },
    experience: 18,
    initiative: 0,
  },
  {
    id: 'thomson',
    campaign: 'c1',
    name: 'Thomson Anning',
    acl: {
      'phil.bowen@gmail.com': 'admin',
    },
    description: '',
    type: 'player',
    attributes: {
      health: attr(10, 0, 'health'),
      might: attr(5, 0, 'might'),
      speed: attr(10, 1, 'speed'),
      focus: attr(7, 1, 'focus'),
      conviction: attr(5, 0, 'conviction'),
    },
    skills: {
      ...playerTemplate.skills,
      movement: skill('movement', 'proficient'),
      riding: skill('riding', 'proficient'),
      piloting: skill('piloting', 'proficient'),
      swimming: skill('swimming', 'proficient'),
      sneaking: skill('sneaking', 'proficient'),
      speeddefense: skill('speeddefense', 'proficient'),
      healthdefense: skill('healthdefense', 'proficient'),
      initiative: skill('initiative', 'proficient'),
      wildernesslore: skill('wildernesslore', 'proficient'),
      medicine: skill('medicine', 'proficient'),
      commandanimal: skill('commandanimal', 'proficient'),
      perception: skill('perception', 'proficient'),
      persuade: skill('persuade', 'proficient'),
      lie: skill('lie', 'proficient'),
      intimidate: skill('intimidate', 'proficient'),
      sensemotive: skill('sensemotive', 'proficient'),
      legerdemain: skill('legerdemain', 'inept'),
      hacking: skill('hacking', 'inept'),
      picklocks: skill('picklocks', 'inept'),
      advancedsecurity: skill('advancedsecurity', 'inept'),
    },
    experience: 16,
    initiative: 0,
  },
];

export const companions: Companion[] = [
  {
    id: 'sparks',
    campaign: 'c1',
    name: 'Sparks',
    description: 'Ornithomimid',
    acl: {
      'cljacobs1975@gmail.com': 'admin',
      'eric.eslinger+tales@gmail.com': 'admin',
    },
    type: 'companion',
    attack: 2,
    defend: 2,
    armor: 0,
    attributes: {
      health: attr(12, 0, 'health'),
      loyalty: attr(8, 0, 'loyalty'),
    },
    initiative: 0,
    baseInitiative: 4,
    skills: {},
    abilities: ['hands', 'birdseye'],
  },
  {
    id: 'biscuit',
    campaign: 'c1',
    name: 'Biscuit',
    description: 'Ankylosaur',
    acl: {
      'megan@albertelli.com': 'admin',
    },
    type: 'companion',
    attack: 2,
    defend: 2,
    armor: 6,
    attributes: {
      health: attr(12, 0, 'health'),
      loyalty: attr(6, 0, 'loyalty'),
    },
    initiative: 0,
    baseInitiative: 4,
    skills: {},
    abilities: [
      'temporalHunter',
      'boneBreaker',
      'sturdyMount',
      'mountedWeapon',
    ],
  },
  {
    id: 'drFanta',
    campaign: 'c1',
    name: 'Dr. Fantabulous',
    description: 'Centrosaurus',
    acl: {
      'llahwehttam@gmail.com': 'admin',
    },
    type: 'companion',
    attack: 1,
    defend: 6,
    armor: 10,
    attributes: {
      health: attr(14, 0, 'health'),
      loyalty: attr(6, 0, 'loyalty'),
    },
    initiative: 0,
    baseInitiative: 4,
    skills: {},
    abilities: ['terrify', 'sturdyMount', 'mountedWeapon'],
  },
  {
    id: 'smammal',
    campaign: 'c1',
    name: 'Smammal',
    description: 'Small Mammal and Occasional Plot Device',
    acl: {
      'guy@albertelli.com': 'admin',
    },
    type: 'companion',
    attack: 1,
    defend: 3,
    armor: 0,
    attributes: {
      health: attr(8, 0, 'health'),
      loyalty: attr(4, 0, 'loyalty'),
    },
    initiative: 0,
    baseInitiative: 4,
    skills: {},
    abilities: ['hands', 'makingTheGMRegretHisLifeChoices'],
  },
  {
    id: 'nugget',
    campaign: 'c1',
    name: 'Nugget 2.0',
    description: 'Raptor',
    acl: {
      'phil.bowen@gmail.com': 'admin',
    },
    type: 'companion',
    attack: 4,
    defend: 1,
    armor: 2,
    attributes: {
      health: attr(15, 0, 'health'),
      loyalty: attr(5, 0, 'loyalty'),
    },
    initiative: 0,
    baseInitiative: 4,
    skills: {},
    abilities: [],
  },
];
