import { Character, Companion, PlayerCharacter } from '../../types/character';
import { attr, skillBlock } from './util';
import { commonSkills, companionBaseSkills } from './skills';

import { Campaign } from '../../types/campaign';
import { Skill } from '../../types/skill';

const localSkills: Skill[] = [
  {
    skillId: 'advancedsecurity',
    type: 'noncombat',
    description: '',
    category: 'adventuring',
    name: 'Advanced Security',
    attributes: ['focus', 'conviction'],
  },
  {
    skillId: 'dryscienceknowledge',
    type: 'noncombat',
    description: '',
    category: 'knowledge',
    name: 'Dry Science Knowledge',
    attributes: ['conviction', 'focus'],
  },
  {
    skillId: 'drysciencetinker',
    type: 'noncombat',
    description: '',
    category: 'knowledge',
    name: 'Dry Science Tinker',
    attributes: ['conviction', 'focus'],
  },
  {
    skillId: 'hacking',
    type: 'noncombat',
    description: '',
    category: 'adventuring',
    name: 'Hacking',
    attributes: ['conviction', 'focus'],
  },
  {
    skillId: 'piloting',
    type: 'noncombat',
    description: '',
    category: 'movement',
    name: 'Piloting',
    attributes: ['speed', 'conviction', 'focus'],
  },
  {
    skillId: 'wetscienceknowledge',
    type: 'noncombat',
    description: '',
    category: 'knowledge',
    name: 'Wet Science Knowledge',
    attributes: ['conviction', 'focus'],
  },
  {
    skillId: 'wetsciencetinker',
    type: 'noncombat',
    description: '',
    category: 'knowledge',
    name: 'Wet Science Tinker',
    attributes: ['conviction', 'focus'],
  },
];

export const campaign: Omit<Campaign, 'campaignId'> = {
  type: 'campaign',
  name: 'Tales of Dinosaurs and Stuff',
  description: 'also Time Travel and Alien Spaceships',
  acl: {},
  skills: commonSkills.concat(localSkills),
};

const players: Omit<PlayerCharacter, 'characterId' | 'campaignId'>[] = [
  {
    name: 'Ry McGinnis',
    acl: {},
    description: '',
    type: 'character',
    subtype: 'player',
    attributes: {
      health: attr(10, 0, 'health'),
      might: attr(5, 0, 'might'),
      speed: attr(5, 0, 'speed'),
      focus: attr(10, 1, 'focus'),
      conviction: attr(7, 0, 'conviction'),
    },
    skills: skillBlock(campaign.skills, {
      inept: [],
      proficient: [
        'dryscienceknowledge',
        'drysciencetinker',
        'combatprediction',
        'hacking',
        'health',
        'tactics',
        'jumpy',
        'providence',
        'legerdemain',
        'toughness',
        'movement',
        'perception',
        'persuade',
        'picklocks',
        'piloting',
        'sensemotive',
        'sneaking',
        'dodge',
        'commandanimal',
        'faith',
      ],
      trained: ['advancedsecurity'],
      expert: [],
    }),
    equipment: [],
    experience: 27,
    initiative: 0,
  },
  {
    name: 'Connecticut (Connie) Butler',
    acl: {},
    description: '',
    type: 'character',
    subtype: 'player',
    attributes: {
      health: attr(10, 0, 'health'),
      might: attr(5, 0, 'might'),
      speed: attr(5, 0, 'speed'),
      focus: attr(7, 0, 'focus'),
      conviction: attr(10, 2, 'conviction'),
    },
    skills: skillBlock(campaign.skills, {
      inept: [
        'dryscienceknowledge',
        'drysciencetinker',
        'wetscienceknowledge',
        'wetsciencetinker',
      ],
      proficient: [
        'health',
        'legerdemain',
        'lie',
        'medicine',
        'toughness',
        'otherknowledge',
        'perception',
        'persuade',
        'sneaking',
        'wildernesslore',
      ],
      trained: ['advancedsecurity'],
      expert: [],
    }),
    equipment: [],
    experience: 34,
    initiative: 0,
  },
  {
    name: 'Momentus Undergrave',
    acl: {},
    description: '',
    type: 'character',
    subtype: 'player',
    attributes: {
      health: attr(10, 0, 'health'),
      might: attr(5, 0, 'might'),
      speed: attr(7, 0, 'speed'),
      focus: attr(10, 1, 'focus'),
      conviction: attr(5, 0, 'conviction'),
    },
    skills: skillBlock(campaign.skills, {
      inept: [
        'dryscienceknowledge',
        'drysciencetinker',
        'wetscienceknowledge',
        'wetsciencetinker',
      ],
      proficient: [
        'health',
        'legerdemain',
        'lie',
        'medicine',
        'toughness',
        'otherknowledge',
        'perception',
        'persuade',
        'sneaking',
        'wildernesslore',
      ],
      trained: ['advancedsecurity'],
      expert: [],
    }),
    equipment: [],
    experience: 22,
    initiative: 0,
  },
  {
    name: 'Chad',
    acl: {},
    description: '',
    type: 'character',
    subtype: 'player',
    attributes: {
      health: attr(10, 0, 'health'),
      might: attr(10, 2, 'might'),
      speed: attr(6, 1, 'speed'),
      focus: attr(5, 0, 'focus'),
      conviction: attr(7, 0, 'conviction'),
    },
    skills: skillBlock(campaign.skills, {
      inept: [
        'dryscienceknowledge',
        'drysciencetinker',
        'wetscienceknowledge',
        'wetsciencetinker',
      ],
      proficient: [
        'health',
        'legerdemain',
        'lie',
        'medicine',
        'toughness',
        'otherknowledge',
        'perception',
        'persuade',
        'sneaking',
        'wildernesslore',
      ],
      trained: ['advancedsecurity'],
      expert: [],
    }),
    equipment: [],
    experience: 18,
    initiative: 0,
  },
  {
    name: 'Thomson Anning',
    acl: {},
    description: '',
    type: 'character',
    subtype: 'player',
    attributes: {
      health: attr(10, 0, 'health'),
      might: attr(5, 0, 'might'),
      speed: attr(10, 1, 'speed'),
      focus: attr(7, 1, 'focus'),
      conviction: attr(5, 0, 'conviction'),
    },
    skills: skillBlock(campaign.skills, {
      inept: [
        'dryscienceknowledge',
        'drysciencetinker',
        'wetscienceknowledge',
        'wetsciencetinker',
      ],
      proficient: [
        'health',
        'legerdemain',
        'lie',
        'medicine',
        'toughness',
        'otherknowledge',
        'perception',
        'persuade',
        'sneaking',
        'wildernesslore',
      ],
      trained: ['advancedsecurity'],
      expert: [],
    }),
    equipment: [],
    experience: 16,
    initiative: 0,
  },
];

export const companions: Omit<Companion, 'characterId' | 'campaignId'>[] = [
  {
    name: 'Sparks',
    description: 'Ornithomimid',
    acl: {},
    type: 'character',
    subtype: 'companion',
    attack: 2,
    defend: 2,
    armor: 0,
    attributes: {
      health: attr(12, 0, 'health'),
      loyalty: attr(8, 0, 'loyalty'),
    },
    skills: companionBaseSkills(),
    initiative: 0,
    equipment: [],
    baseInitiative: 4,
    abilities: ['hands', 'birdseye'],
  },
  {
    name: 'Biscuit',
    description: 'Ankylosaur',
    acl: {},
    type: 'character',
    subtype: 'companion',
    attack: 2,
    defend: 2,
    armor: 6,
    skills: companionBaseSkills(),
    attributes: {
      health: attr(12, 0, 'health'),
      loyalty: attr(6, 0, 'loyalty'),
    },
    initiative: 0,
    equipment: [],
    baseInitiative: 4,
    abilities: [
      'temporalHunter',
      'boneBreaker',
      'sturdyMount',
      'mountedWeapon',
    ],
  },
  {
    name: 'Dr. Fantabulous',
    description: 'Centrosaurus',
    acl: {},
    type: 'character',
    subtype: 'companion',
    attack: 1,
    defend: 6,
    armor: 10,
    attributes: {
      health: attr(14, 0, 'health'),
      loyalty: attr(6, 0, 'loyalty'),
    },
    skills: companionBaseSkills(),
    initiative: 0,
    equipment: [],
    baseInitiative: 4,
    abilities: ['terrify', 'sturdyMount', 'mountedWeapon'],
  },
  {
    name: 'Smammal',
    description: 'Small Mammal and Occasional Plot Device',
    acl: {},
    type: 'character',
    subtype: 'companion',
    attack: 1,
    defend: 3,
    armor: 0,
    attributes: {
      health: attr(8, 0, 'health'),
      loyalty: attr(4, 0, 'loyalty'),
    },
    skills: companionBaseSkills(),
    initiative: 0,
    equipment: [],
    baseInitiative: 4,
    abilities: ['hands', 'makingTheGMRegretHisLifeChoices'],
  },
  {
    name: 'Nugget 2.0',
    description: 'Raptor',
    acl: {},
    type: 'character',
    subtype: 'companion',
    skills: companionBaseSkills(),
    attack: 4,
    defend: 1,
    armor: 2,
    attributes: {
      health: attr(15, 0, 'health'),
      loyalty: attr(5, 0, 'loyalty'),
    },
    initiative: 0,
    equipment: [],
    baseInitiative: 4,
    abilities: [],
  },
];

export const characters = players.concat(companions as any) as Omit<
  Character,
  'campaignId' | 'characterId'
>[];
