import { attr, skillBlock } from './util';
import {
  crossbow,
  dagger,
  feet,
  lightMace,
  longbow,
  magicCrossbow,
  magicRapier,
  shield,
  staff,
  stoneCloak,
} from './equipment';

import { Campaign } from '../../types/campaign';
import { PlayerCharacter } from '../../types/character';
import { Skill } from '../../types/skill';
import { commonSkills } from './skills';

const localSkills: Skill[] = [
  {
    skillId: 'arcaneknowledge',
    type: 'noncombat',
    description: '',
    name: 'Arcane Knowledge',
    category: 'magic',
    attributes: ['conviction'],
  },
  {
    skillId: 'arcanetinker',
    type: 'noncombat',
    description: '',
    category: 'magic',
    name: 'Arcane Tinker',
    attributes: ['conviction'],
  },
  {
    skillId: 'alchemyknowledge',
    type: 'noncombat',
    description: '',
    category: 'magic',
    name: 'Alchemy Knowledge',
    attributes: ['conviction', 'focus'],
  },
  {
    skillId: 'alchemytinker',
    type: 'noncombat',
    category: 'magic',
    description: '',
    name: 'Alchemy Tinker',
    attributes: ['conviction', 'focus'],
  },
  {
    skillId: 'divineknowledge',
    type: 'noncombat',
    category: 'magic',
    description: '',
    name: 'Divine Knowledge',
    attributes: ['conviction'],
  },
  {
    skillId: 'divinetinker',
    type: 'noncombat',
    category: 'magic',
    description: '',
    name: 'Divine Tinker',
    attributes: ['conviction'],
  },
  {
    skillId: 'psionicknowledge',
    type: 'noncombat',
    category: 'magic',
    description: '',
    name: 'Psionic Knowledge',
    attributes: ['conviction', 'focus'],
  },
  {
    skillId: 'psionictinker',
    type: 'noncombat',
    description: '',
    category: 'magic',
    name: 'Psionic Tinker',
    attributes: ['conviction', 'focus'],
  },
  {
    skillId: 'traps',
    type: 'noncombat',
    description: '',
    category: 'adventuring',
    name: 'Traps',
    attributes: ['conviction', 'focus'],
  },
];

export const campaign: Omit<Campaign, 'campaignId'> = {
  type: 'campaign',
  name: 'Tales of Fantasy and Fighting',
  description: 'also Underground Caverns and Chaos',
  acl: {},
  skills: commonSkills.concat(localSkills),
};

export const characters: PlayerCharacter[] = [
  {
    name: 'Stu Roid',
    campaignId: 'ou',
    characterId: 'stu',
    acl: {},
    description: '',
    type: 'character',
    subtype: 'player',
    attributes: {
      health: attr(10, 0, 'health'),
      might: attr(6, 0, 'might'),
      speed: attr(6, 0, 'speed'),
      focus: attr(12, 2, 'focus'),
      conviction: attr(6, 0, 'conviction'),
    },
    skills: skillBlock(campaign.skills, {
      inept: ['commandanimal', 'legerdemain', 'picklocks'],
      proficient: [
        'medicine',
        'alchemyknowledge',
        'alchemytinker',
        'combatinsight',
        'sniper',
        'health',
        'combatprediction',
      ],
      trained: [],
      expert: [],
    }),
    experience: 1,
    initiative: 0,
    equipped: [stoneCloak, crossbow, dagger, shield, staff],
    carried: [],
    abilities: [],
  },
  {
    name: 'Kewulf Trannyth',
    campaignId: 'ou',
    characterId: 'kewulf',
    acl: {},
    description: '',
    type: 'character',
    subtype: 'player',
    attributes: {
      health: attr(10, 0, 'health'),
      might: attr(6, 0, 'might'),
      speed: attr(8, 0, 'speed'),
      focus: attr(5, 0, 'focus'),
      conviction: attr(11, 1, 'conviction'),
    },
    skills: skillBlock(campaign.skills, {
      inept: [
        'arcanetinker',
        'religiontinker',
        'psionicknowledge',
        'psionictinker',
      ],
      proficient: ['sneaking', 'perception', 'hipshot', 'dodge'],
      trained: [],
      expert: [],
    }),
    experience: 5,
    initiative: 0,
    equipped: [longbow, stoneCloak, dagger],
    carried: [],
    abilities: [],
  },
  {
    name: 'Malven Stonecutter',
    campaignId: 'ou',
    characterId: 'malven',
    acl: {},
    description: '',
    type: 'character',
    subtype: 'player',
    attributes: {
      health: attr(10, 0, 'health'),
      might: attr(6, 0, 'might'),
      speed: attr(9, 0, 'speed'),
      focus: attr(9, 1, 'focus'),
      conviction: attr(6, 0, 'conviction'),
    },
    skills: skillBlock(campaign.skills, {
      inept: [
        'wildernesslore',
        'arcaneknowledge',
        'religiousknowledge',
        'commandanimal',
      ],
      proficient: [
        'sneaking',
        'picklocks',
        'traps',
        'combatprediction',
        'health',
        'fencing',
      ],
      trained: [],
      expert: [],
    }),
    experience: 5,
    initiative: 0,
    equipped: [lightMace, stoneCloak, dagger],
    carried: [],
    abilities: [],
  },
  {
    name: 'Jordiz Shirodz',
    campaignId: 'ou',
    characterId: 'jordiz',
    acl: {},
    description: '',
    type: 'character',
    subtype: 'player',
    attributes: {
      health: attr(10, 0, 'health'),
      might: attr(6, 0, 'might'),
      speed: attr(8, 1, 'speed'),
      focus: attr(11, 1, 'focus'),
      conviction: attr(5, 0, 'conviction'),
    },
    skills: skillBlock(campaign.skills, {
      inept: ['riding', 'wildernesslore', 'lie', 'picklocks'],
      proficient: [
        'fencing',
        'quickshot',
        'combatprediction',
        'health',
        'movement',
      ],
      trained: [],
      expert: [],
    }).concat([
      {
        level: 'proficient',
        skillId: 'unarmed',
        name: 'Unarmed Combat',
        category: 'melee',
        attributes: ['focus', 'speed', 'might', 'conviction'],
        type: 'attack',
        description: 'attacking with hands and feet',
      },
    ]),
    experience: 5,
    initiative: 0,
    equipped: [stoneCloak],
    carried: [],
    abilities: [feet],
  },
  {
    name: 'Cantaloupe "Loupe" Pantaloons',
    campaignId: 'ou',
    characterId: 'loupe',
    acl: {},
    description: '',
    type: 'character',
    subtype: 'player',
    attributes: {
      health: attr(10, 0, 'health'),
      might: attr(5, 0, 'might'),
      speed: attr(11, 2, 'speed'),
      focus: attr(8, 0, 'focus'),
      conviction: attr(6, 0, 'conviction'),
    },
    skills: skillBlock(campaign.skills, {
      inept: ['riding', 'medicine', 'commandanimal', 'persuade'],
      proficient: ['fencing', 'dodge', 'reflexes', 'health', 'movement'],
      trained: [],
      expert: [],
    }),
    experience: 5,
    initiative: 0,
    equipped: [magicRapier, stoneCloak, magicCrossbow],
    carried: [],
    abilities: [],
  },
];
