import { Skill } from '../../types/skill';

export const skillSeed: Record<string, Skill> = {
  advancedsecurity: {
    id: 'advancedsecurity',
    type: 'noncombat',
    description: '',
    name: 'Advanced Security',
    attributes: ['focus', 'conviction'],
  },
  commandanimal: {
    id: 'commandanimal',
    type: 'noncombat',
    description: '',
    name: 'Command Animal',
    attributes: ['conviction', 'focus'],
  },
  convictiondefense: {
    id: 'convictiondefense',
    type: 'noncombat',
    description: '',
    name: 'Conviction Defense',
    attributes: ['conviction'],
  },
  convictionmeleeattack: {
    id: 'convictionmeleeattack',
    type: 'noncombat',
    description: '',
    name: 'Conviction Melee Attack',
    attributes: ['conviction'],
  },
  convictionrangedattack: {
    id: 'convictionrangedattack',
    type: 'noncombat',
    description: '',
    name: 'Conviction Ranged Attack',
    attributes: ['conviction'],
  },
  dryscienceknowledge: {
    id: 'dryscienceknowledge',
    type: 'noncombat',
    description: '',
    name: 'Dry Science Knowledge',
    attributes: ['conviction', 'focus'],
  },
  drysciencetinker: {
    id: 'drysciencetinker',
    type: 'noncombat',
    description: '',
    name: 'Dry Science Tinker',
    attributes: ['conviction', 'focus'],
  },
  focusdefense: {
    id: 'focusdefense',
    type: 'noncombat',
    description: '',
    name: 'Focus Defense',
    attributes: ['focus'],
  },
  focusmeleeattack: {
    id: 'focusmeleeattack',
    type: 'noncombat',
    description: '',
    name: 'Focus Melee Attack',
    attributes: ['focus'],
  },
  focusrangedattack: {
    id: 'focusrangedattack',
    type: 'noncombat',
    description: '',
    name: 'Focus Ranged Attack',
    attributes: ['focus'],
  },
  hacking: {
    id: 'hacking',
    type: 'noncombat',
    description: '',
    name: 'Hacking',
    attributes: ['conviction', 'focus'],
  },
  healthdefense: {
    id: 'healthdefense',
    type: 'noncombat',
    description: '',
    name: 'Health Defense',
    attributes: ['health'],
  },
  initiative: {
    id: 'initiative',
    type: 'noncombat',
    description: '',
    name: 'Initiative',
    attributes: ['conviction', 'speed', 'focus', 'might'],
  },
  intimidate: {
    id: 'intimidate',
    type: 'noncombat',
    description: '',
    name: 'Intimidate',
    attributes: ['conviction', 'might'],
  },
  legerdemain: {
    id: 'legerdemain',
    type: 'noncombat',
    description: '',
    name: 'Legerdemain',
    attributes: ['speed'],
  },
  lie: {
    id: 'lie',
    type: 'noncombat',
    description: '',
    name: 'Lie',
    attributes: ['conviction'],
  },
  medicine: {
    id: 'medicine',
    type: 'noncombat',
    description: '',
    name: 'Medicine',
    attributes: ['conviction', 'focus'],
  },
  mightdefense: {
    id: 'mightdefense',
    type: 'noncombat',
    description: '',
    name: 'Might Defense',
    attributes: ['might'],
  },
  mightmeleeattack: {
    id: 'mightmeleeattack',
    type: 'noncombat',
    description: '',
    name: 'Might Melee Attack',
    attributes: ['might'],
  },
  mightrangedattack: {
    id: 'mightrangedattack',
    type: 'noncombat',
    description: '',
    name: 'Might Ranged Attack',
    attributes: ['might'],
  },
  movement: {
    id: 'movement',
    type: 'noncombat',
    description: '',
    name: 'Movement',
    attributes: ['might', 'speed'],
  },
  otherknowledge: {
    id: 'otherknowledge',
    type: 'noncombat',
    description:
      'Any knowledge that does not fall under Wet Science or Dry Science',
    name: 'Knowledge',
    attributes: ['focus', 'conviction'],
  },
  perception: {
    id: 'perception',
    type: 'noncombat',
    description: '',
    name: 'Perception',
    attributes: ['conviction', 'focus'],
  },
  persuade: {
    id: 'persuade',
    type: 'noncombat',
    description: '',
    name: 'Persuade',
    attributes: ['focus'],
  },
  picklocks: {
    id: 'picklocks',
    type: 'noncombat',
    description: '',
    name: 'Pick Locks',
    attributes: ['speed', 'focus', 'conviction'],
  },
  piloting: {
    id: 'piloting',
    type: 'noncombat',
    description: '',
    name: 'Piloting',
    attributes: ['speed', 'conviction', 'focus'],
  },
  riding: {
    id: 'riding',
    type: 'noncombat',
    description: '',
    name: 'Riding',
    attributes: ['speed', 'conviction'],
  },
  sensemotive: {
    id: 'sensemotive',
    type: 'noncombat',
    description: '',
    name: 'Sense Motive',
    attributes: ['focus'],
  },
  sneaking: {
    id: 'sneaking',
    type: 'noncombat',
    description: '',
    name: 'Sneaking',
    attributes: ['speed', 'focus'],
  },
  speeddefense: {
    id: 'speeddefense',
    type: 'noncombat',
    description: '',
    name: 'Speed Defense',
    attributes: ['speed'],
  },
  speedmeleeattack: {
    id: 'speedmeleeattack',
    type: 'noncombat',
    description: '',
    name: 'Speed Melee Attack',
    attributes: ['speed'],
  },
  speedrangedattack: {
    id: 'speedrangedattack',
    type: 'noncombat',
    description: '',
    name: 'Speed Ranged Attack',
    attributes: ['speed'],
  },
  swimming: {
    id: 'swimming',
    type: 'noncombat',
    description: '',
    name: 'Swimming',
    attributes: ['might'],
  },
  wetscienceknowledge: {
    id: 'wetscienceknowledge',
    type: 'noncombat',
    description: '',
    name: 'Wet Science Knowledge',
    attributes: ['conviction', 'focus'],
  },
  wetsciencetinker: {
    id: 'wetsciencetinker',
    type: 'noncombat',
    description: '',
    name: 'Wet Science Tinker',
    attributes: ['conviction', 'focus'],
  },
  wildernesslore: {
    id: 'wildernesslore',
    type: 'noncombat',
    description: '',
    name: 'Wilderness Lore',
    attributes: ['conviction', 'focus'],
  },
};
