import { Campaign, NewCampaign } from '../../types/campaign';

export const campaignTemplate: NewCampaign = {
  name: '',
  description: '',
  acl: {},
  skills: [],
  characters: [],
};

export const campaign: Campaign = {
  id: 'c1',
  name: 'Tales of Dinosaurs and Stuff',
  description: 'also Time Travel and Alien Spaceships',
  characters: [
    'ry',
    'connie',
    'momentusUndergrave',
    'chad',
    'thomson',
    'sparks',
    'biscuit',
    'drFanta',
    'smammal',
    'nugget',
  ],
  acl: {
    'eric.eslinger@gmail.com': 'admin',
    'albertel@gmail.com': 'read',
    'malbertelli@gmail.com': 'read',
    'llahwehttam@gmail.com': 'read',
    'guy@albertelli.com': 'read',
    'megan@albertelli.com': 'read',
    'chrissy.jacobs@sfuhs.org': 'read',
    'phil.bowen@gmail.com': 'read',
    'cljacobs1975@gmail.com': 'read',
  },
  skills: [
    'advancedSecurity',
    'commandAnimal',
    'convictionDefense',
    'convictionMeleeAttack',
    'convictionRangedAttack',
    'dryScienceKnowledge',
    'dryScienceTinker',
    'focusDefense',
    'focusMeleeAttack',
    'focusRangedAttack',
    'hacking',
    'healthDefense',
    'initiative',
    'intimidate',
    'legerdemain',
    'lie',
    'medicine',
    'mightDefense',
    'mightMeleeAttack',
    'mightRangedAttack',
    'movement',
    'otherKnowledge',
    'perception',
    'persuade',
    'pickLocks',
    'piloting',
    'riding',
    'senseMotive',
    'sneaking',
    'speedDefense',
    'speedMeleeAttack',
    'speedRangedAttack',
    'swimming',
    'wetScienceKnowledge',
    'wetScienceTinker',
    'wildernessLore',
  ],
};
